version: "3.8"
services:
  chatwave-frontend:
    env_file:
      - .envfrontend-nextjs.env
    build: ./chatwave-frontend
    ports:
      - "3000:3000"
    networks:
      - chatwave-net
    volumes:
      - ./chatwave-frontend:/chatwave-frontend

  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - chatwave-net
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks:
  chatwave-net:
    driver: bridge
    name: cruddur-net
volumes:
  db:
    driver: local
