projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: s2izn4yczffbvhv7rppmldbk7e
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
